language: c
before_install:
  - sudo apt-get install bc
  - curl -O http://fishshell.com/files/2.1.0/linux/Ubuntu/fish_2.1.0-1~precise_amd64.deb
  - sudo dpkg --install fish_2.1.0-1~precise_amd64.deb
  - git clone git://github.com/terlar/fish-tank.git
  - cd fish-tank
  - sudo make install
  - cd -

script: make test
